### ISSUE TITLE
Encoding functions

### ISSUE THREAD

**Issue by jariji** [davibarreira/Vizagrams.jl#16]
@aplavin had a good idea for Makie to support functions that map each row to its plot value. In Vizagrams I think it would be something like

```jl

Plot(
  data=df,
  encodings=(;
    x=(;value = row ->  log(row.a)),
    y=(;value = row -> row.b^2),
    color=(;value = row -> row.c),
  ),
)
```

To be ambitious it could even take the text for the axis label from an Accessors.jl optic expression.

```jl
using Accessors

# `@o f(_.a)` is just Accessors.jl syntax for a a callable like `row -> f(row.a)`.

Plot(
  data=df,
  encodings=(;
    x=(;value=@o log(_.a)),
    y=(;value=@o _.b^2),
    color=(;value=@o _.c),
  ),
)
```

**Comment by davibarreira** [comment]
I think the package already cover this:
```julia
df = StructArray(x = 10*rand(10),y=rand(10))
plt = plot(
    df,
    x=(field=:x,scale=x->log(x)),
    y=(field=:y,scale=y->y^2)
)
```

Would this be the same thing you have in mind?

**Comment by davibarreira** [comment]
I guess one could write:
```Julia
df = StructArray(a = rand(5), b=rand(5))
plot(
    x= map(row->row.a^2 + row.b^2, df),
    y= map(row->log(row.a),df)
)
```
Although, I do see the appeal of reducing this clutter. I think I can add this functionality in the quick plot.

Just to be clear, in Vizagrams the `Plot` struct contains a `PlotSpec`, which is the "formal" specification of how to map the dataset to visual variables. The way one maps the data to the visual variable if formally done via a scaling function, and (in theory) it should not mix distinct columns. We can "bypass" this formalism by instead assuming that the dataset is being transformed before specifying the plot.

Perhaps you noticed that one can create a plot using either `Plot` or `plot`. At the moment, `plot` is a function designed to create plots quickly, without having to give the full specification (hence why it lacks the `encodings` field).
I think I can add your idea to the `plot` function, so that what it will do is apply the transformations to the dataset, creating new columns and then doing the specification.

**Comment by jariji** [comment]
Does `PlotSpec` need to have a `field=`, or can it take the raw value so that `x=(;scale=log)` is supported on `data=rand(10)`?

**Comment by davibarreira** [comment]
Yes, the `field` is necessary. PlotSpec is modeled after Vega-Lite specification, which is based on the Grammar of Graphics, which is a theory about how to properly specify visualizations. This rigidity comes to "guarantee" that the produced visualization is "correct". Yet, in practice, we usually know the underlying context, and want to avoid this strict formalism.
This is why I have the `plot` function. It allows users to quickly create plots without properly specifying them. Hence, you can just write:
```
plot(x=rand(10), y=rand(10))
```
And this will work. But what is happening is that, under the hood, I'm creating a StructArray with columns `x` and `y`. Then, I create the full specification. To solve your issue, I'd go about with the same strategy. First apply the functions, create new columns, and then specify the plot correctly (using `field` and all the rest).
